export const COIN_RECEIVED = 'COIN RECEIVED'
export const FAILURE = 'FAILED'
export const PLAY_PUZZLE = 'PLAY PUZZLE'
export const RECEIVE_COIN = 'RECEIVE COIN'
export const SHOPEE_REWARD = 'SHOPEE REWARD'
export const TOO_MUCH_TRY = 'TOO MUCH TRY'
export const USE_LINK = 'USE LINK'
export const USE_EMAIL_LINK = 'USE EMAIL LINK'
export const WRONG_PASSWORDS = [
  'WRONG PASSWORD 1',
  'WRONG PASSWORD 2',
  'WRONG PASSWORD 3'
]
