name: Publish

on:
  workflow_dispatch: ~
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  unittests:
    uses: ./.github/workflows/unittests.yaml

  build:
    name: Build project and push image to dockerhub and ghcr
    needs:
      - unittests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Install dependencies
        run: pnpm install --prod
      - name: Build project
        run: pnpm build
      - name: Build kelly image
        uses: wdzeng/image@v2
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          variant: kelly
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=alpine-base
            VARIANT=kelly
          repo-description: Get Shopee coins everyday
          repo-license: MIT
      - name: Build regular image
        uses: wdzeng/image@v2
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          init: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=alpine-font
            VARIANT=''
          repo-description: Get Shopee coins everyday
          repo-license: MIT

  tag:
    name: Add tags to repository
    if: ${{ github.event_name == 'push' }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: version
        uses: wdzeng/version@v1
        with:
          prefix: v
      - name: Add tags
        run: |
          git tag -f ${{ steps.version.outputs.version }} main && \
          git push -f origin ${{ steps.version.outputs.version }}
