name: Unittests

on:
  workflow_dispatch: ~
  push:
    branches:
      - dev
    paths:
      - src/**
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 22 * * 1'  # 06:00 AM +08:00 every Monday
  workflow_call: ~

jobs:
  unittests:
    name: Run unittests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v2
        with:
          run_install: true
      - name: Run unittests
        run: pnpm test
